# Generated by Django 6.0.2 on 2026-02-23 18:29

import caverne.models
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(verbose_name='nom du fichier')),
                ('description', models.TextField()),
                ('year', models.IntegerField(choices=[(1, '1re'), (2, '2e'), (3, '3e'), (4, '4e')], verbose_name='années')),
                ('subject', models.CharField(choices=[('AN', 'Anglais'), ('BI', 'Biologie'), ('FR', 'Français'), ('GE', 'Géographie'), ('HI', 'Histoire'), ('IT', 'Italien'), ('MA', 'Mathématiques'), ('PY', 'Physique'), ('AM', 'Applications des maths'), ('PO', 'Philosophie')], verbose_name='matière')),
                ('status', models.CharField(default='PENDING')),
                ('tags', models.TextField(verbose_name='mots clés')),
                ('uploadDatetime', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('file', models.FileField(upload_to=caverne.models.Fichier.filePlacer, verbose_name='fichier')),
                ('user', models.ForeignKey(on_delete=models.SET(caverne.models.Fichier.get_sentinel_user), related_name='fichiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
