# Generated by Django 6.0.2 on 2026-03-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0002_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='ecole',
            field=models.CharField(choices=[('CHAVANNE', 'Collège et Ecole de commerce André-Chavanne'), ('CALVIN', 'Collège Calvin'), ('CLAPAREDE', 'Collège Claparède'), ('CANDOLLE', 'Collège de Candolle'), ('SAUSSURE', 'Collège de Saussure'), ('EMILIE', 'Collège Emilie-Gourd'), ('STAEL', 'Collège Madame de Staël'), ('RIVAZ', 'Collège pour adultes Alice-Rivaz'), ('ROUSSEAU', 'Collège Rousseau'), ('SISMONDI', 'Collège Sismondi'), ('VOLTAIRE', 'Collège Voltaire')], default='SISMONDI', verbose_name='collège'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='enseignant',
            field=models.CharField(default='SCHIESS', verbose_name='enseignant.e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='type',
            field=models.CharField(choices=[('EVAL', 'Évaluation'), ('THEO', 'Théorie'), ('EXOS', 'Exercices')], default='EVAL', verbose_name='type de fichier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ecole',
            field=models.CharField(choices=[('CHAVANNE', 'Collège et Ecole de commerce André-Chavanne'), ('CALVIN', 'Collège Calvin'), ('CLAPAREDE', 'Collège Claparède'), ('CANDOLLE', 'Collège de Candolle'), ('SAUSSURE', 'Collège de Saussure'), ('EMILIE', 'Collège Emilie-Gourd'), ('STAEL', 'Collège Madame de Staël'), ('RIVAZ', 'Collège pour adultes Alice-Rivaz'), ('ROUSSEAU', 'Collège Rousseau'), ('SISMONDI', 'Collège Sismondi'), ('VOLTAIRE', 'Collège Voltaire')], verbose_name='collège'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
