# Generated by Django 6.0.2 on 2026-03-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0003_fichier_ecole_fichier_enseignant_fichier_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='annotated',
            field=models.BooleanField(default=False, verbose_name='annoté'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichier',
            name='year',
            field=models.IntegerField(choices=[(1, '1re'), (2, '2e'), (3, '3e'), (4, '4e')], verbose_name='année'),
        ),
    ]
