# Generated by Django 6.0.2 on 2026-03-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0004_fichier_annotated_alter_fichier_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom, prénom')),
                ('ecole', models.CharField(choices=[('CHAVANNE', 'Collège et Ecole de commerce André-Chavanne'), ('CALVIN', 'Collège Calvin'), ('CLAPAREDE', 'Collège Claparède'), ('CANDOLLE', 'Collège de Candolle'), ('SAUSSURE', 'Collège de Saussure'), ('EMILIE', 'Collège Emilie-Gourd'), ('STAEL', 'Collège Madame de Staël'), ('RIVAZ', 'Collège pour adultes Alice-Rivaz'), ('ROUSSEAU', 'Collège Rousseau'), ('SISMONDI', 'Collège Sismondi'), ('VOLTAIRE', 'Collège Voltaire')], verbose_name='collège')),
            ],
        ),
        migrations.AlterField(
            model_name='fichier',
            name='annotated',
            field=models.BooleanField(verbose_name='annoté?'),
        ),
    ]
