# Generated by Django 6.0.2 on 2026-03-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0005_enseignant_alter_fichier_annotated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='status',
            field=models.IntegerField(choices=[(2, 'En attente'), (0, 'Rejeté'), (1, 'Chargé')], default=2),
        ),
    ]
