# Generated by Django 6.0.2 on 2026-05-18 21:19

import caverne.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0006_alter_fichier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='file',
            field=models.FileField(upload_to=caverne.models.filePlacer, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt']), caverne.models.validate_file_mimetype], verbose_name='fichier'),
        ),
    ]
