# Generated by Django 6.0.2 on 2026-06-01 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0008_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), verbose_name='mots clés'),
        ),
    ]
