# Generated by Django 6.0.2 on 2026-06-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0009_alter_fichier_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='mot clé')),
            ],
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='tags',
        ),
        migrations.AddField(
            model_name='fichier',
            name='tags',
            field=models.ManyToManyField(related_name='fichiers', to='caverne.tag'),
        ),
    ]
