# Generated by Django 6.0.2 on 2026-06-08 12:43

import caverne.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0010_tag_remove_fichier_tags_fichier_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='thumbnail',
            field=models.ImageField(default='test', upload_to=caverne.models.thumbnail_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichier',
            name='subject',
            field=models.CharField(choices=[('AL', 'Allemand'), ('AN', 'Anglais'), ('AM', 'Applications des maths'), ('AP', 'Arts plastiques'), ('BI', 'Biologie'), ('CH', 'Chimie'), ('FR', 'Français'), ('GE', 'Géographie'), ('HI', 'Histoire'), ('HA', "Histoire de l'art"), ('IT', 'Italien'), ('MA', 'Mathématiques'), ('PO', 'Philosophie'), ('PY', 'Physique')], verbose_name='matière'),
        ),
    ]
