# Generated by Django 6.0.2 on 2026-06-17 22:54

import caverne.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0011_fichier_thumbnail_alter_fichier_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='enseignant',
            field=models.ForeignKey(on_delete=models.SET(caverne.models.get_sentinel_enseignant), related_name='fichiers', to='caverne.enseignant'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='file',
            field=models.FileField(upload_to=caverne.models.file_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), caverne.models.validate_file_mimetype], verbose_name='fichier'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='status',
            field=models.IntegerField(choices=[(2, 'En attente'), (0, 'Rejeté'), (1, 'Chargé')], default=1),
        ),
    ]
