# Generated by Django 6.0.2 on 2026-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0012_alter_fichier_enseignant_alter_fichier_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='annotated',
            field=models.BooleanField(verbose_name='annoté/corrigé?'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fichiers', to='caverne.tag'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='year',
            field=models.IntegerField(choices=[(1, '1re'), (2, '2e'), (3, '3e'), (4, '4e')], verbose_name='degré'),
        ),
    ]
