# Generated by Django 6.0.2 on 2026-09-18 18:58

from django.contrib.postgres.operations import (
    TrigramExtension,
    UnaccentExtension,
)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0013_alter_fichier_annotated_alter_fichier_description_and_more'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
