# Generated by Django 6.0.2 on 2026-09-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caverne', '0014_enable_postgres_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='subject',
            field=models.CharField(choices=[('AL', 'Allemand'), ('AN', 'Anglais'), ('AM', 'Applications des maths'), ('AP', 'Arts plastiques'), ('BI', 'Biologie'), ('CH', 'Chimie'), ('DR', 'Droit'), ('EC', 'Économie'), ('FR', 'Français'), ('GE', 'Géographie'), ('HI', 'Histoire'), ('HA', "Histoire de l'art"), ('IN', 'Informatique'), ('IT', 'Italien'), ('MA', 'Mathématiques'), ('PO', 'Philosophie'), ('PY', 'Physique')], verbose_name='matière'),
        ),
    ]
